2025-05-24 09:06:18,568 - __main__ - ERROR - Error parsing student data for ID 10034695: HTTPConnectionPool(host='vuz2.bru.by', port=80): Max retries exceeded with url: /rate/10034695/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000161E84BD400>: Failed to resolve 'vuz2.bru.by' ([Errno 11002] getaddrinfo failed)"))
2025-05-24 09:17:23,579 - __main__ - ERROR - Error parsing student data for ID 10034695: HTTPConnectionPool(host='vuz2.bru.by', port=80): Max retries exceeded with url: /rate/10034695/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000148FF4AC050>: Failed to resolve 'vuz2.bru.by' ([Errno 11002] getaddrinfo failed)"))
2025-05-24 09:58:14,440 - __main__ - ERROR - Error parsing student data for ID 10034695: HTTPConnectionPool(host='vuz2.bru.by', port=80): Max retries exceeded with url: /rate/10034695/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000026EA042C050>: Failed to resolve 'vuz2.bru.by' ([Errno 11002] getaddrinfo failed)"))
2025-05-24 10:17:34,612 - __main__ - ERROR - Error parsing student data for ID 10034695: HTTPConnectionPool(host='vuz2.bru.by', port=80): Max retries exceeded with url: /rate/10034695/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000026EA03D6FD0>: Failed to resolve 'vuz2.bru.by' ([Errno 11002] getaddrinfo failed)"))
2025-05-24 11:18:24,462 - __main__ - ERROR - Error parsing student data for ID 10034885: HTTPConnectionPool(host='vuz2.bru.by', port=80): Max retries exceeded with url: /rate/10034885/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000026EA02F7B10>: Failed to resolve 'vuz2.bru.by' ([Errno 11002] getaddrinfo failed)"))
2025-05-24 11:50:07,805 - __main__ - ERROR - Ошибка при парсинге данных студента для ID 10034885: HTTPConnectionPool(host='vuz2.bru.by', port=80): Max retries exceeded with url: /rate/10034885/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000019E7D957A10>: Failed to resolve 'vuz2.bru.by' ([Errno 11002] getaddrinfo failed)"))
2025-05-24 12:56:50,596 - __main__ - ERROR - Ошибка при парсинге данных студента для ID 10034695: HTTPConnectionPool(host='vuz2.bru.by', port=80): Max retries exceeded with url: /rate/10034695/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002745FD44980>: Failed to resolve 'vuz2.bru.by' ([Errno 11002] getaddrinfo failed)"))
